kind: pipeline
type: docker
name: default

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: node_modules
    host:
      path: /home/node/.cache/${DRONE_REPO}/node_modules

trigger:
  branch:
    - main

steps:
  - name: deploy
    image: node:20-alpine
    pull: if-not-exists
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: node_modules
        path: /drone/src/node_modules
    commands:
      - echo "node version:" && node -v && echo "yarn version:" && yarn -v
      - yarn install 

