kind: pipeline
type: docker
name: default

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: node_modules
    host:
      path: /home/node/.cache/${DRONE_REPO}/node_modules
  - name: sprites
    host:
      path: /home/mapbox/sprites

trigger:
  branch:
    - main

steps:
  - name: deploy
    image: docker:dind
    pull: if-not-exists
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: sprites 
        path: /drone/src/sprites
    commands:
      - cd data
      - docker run -e FOLDER=svgs -e THEME=sprites -v /home/mapbox:/data dolomate/spritezero

